# AI Agent Farm - Centralized Logging & Monitoring Stack
# ======================================================
# Grafana Loki + Promtail + Grafana для centralized logging

version: '3.8'

services:
  # 📊 Loki - Log Aggregation System
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
      - ./logging/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - monitoring
    restart: unless-stopped

  # 🚛 Promtail - Log Shipper
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./logging/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - monitoring
    restart: unless-stopped

  # 📈 Grafana - Visualization Dashboard
  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./logging/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./logging/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./logging/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
    networks:
      - monitoring
    restart: unless-stopped

  # 📊 Prometheus - Metrics Collection (опционально)
  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./logging/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  loki_data:
  grafana_data:
  prometheus_data:

networks:
  monitoring:
    external: true
